---
- hosts: kubernetes-master-nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
 
  - name: Allow Network Ports in Firewalld. Configuramos el firewall para acceder a los servicios de kubernetes
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports if ('kubernetes-master-nodes' in group_names) else worker_ports }}"

  - name: Permitiremos el acceso desde los workers
    shell: firewall-cmd --permanent --add-rich-rule 'rule family=ipv4 source address=10.0.2.11/24 accept'
          
  - name: Pulling images required for setting up a Kubernetes cluster. Configuramos kubadm
    shell: kubeadm config images pull

  - name: Resetting kubeadm
    shell: kubeadm reset -f
    register: output

  - name: Initializing Kubernetes cluster
    shell: kubeadm init --apiserver-advertise-address {{ad_addr}} --pod-network-cidr={{cidr_v}}
    register: output

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}
    become: False

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

