---
- hosts: kubernetes-master-nodes:kubernetes-worker-nodes
  become: yes
  vars_files:
  - env_variables
  tasks:
  - name: Creating a repository file for Kubernetes. Configuramoe el repositorio de Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file. Istalamos kubernetes
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Installing Docker and firewalld. Instalamos docker que será el engine para ejecutar contenedores
    shell: |
     yum install firewalld -y
     yum install -y yum-utils device-mapper-persistent-data lvm2
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce -y --nobest

  - name: Installing required packages
    yum:
     name: "{{ packages }}"
     state: present

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

 
  - name: Enabling Bridge Firewall Rule. iptables  Para permitir que kubernetes maneje correctamente el tráfico con el cortafuego
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
 
  - name: Enabling Bridge Firewall Rule. ip6tables Para permitir que kubernetes maneje correctamente el tráfico con el cortafuego
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-ip6tables"
